### ISSUE TITLE
Attribute spread

### ISSUE THREAD

**Issue by dephiros** [WebReflection/ucontent#5]
Hi,

Thank you for your work.
Does `html` support attribute spread?

Thank you

**Comment by WebReflection** [comment]
I don't know what that is hence I guess the answer is no.

**Comment by dephiros** [comment]
@WebReflection , what i meant is something like
```
<div ...${props}>
```
This is taken from `htm` for preact: https://github.com/developit/htm

**Comment by WebReflection** [comment]
Nope, this is the SSR version of uhtml, which is a subset of lighterhtml, and it shares the same parser, so either I change 3 libraries for that use case, or it won't likely be implemented. See uparser
